### ISSUE TITLE
Xacro include filename with relative path, will not work if other packages want to reuse xacro

### ISSUE THREAD

**Issue by hsu** [NASA-JSC-Robotics/val_description#16] opened 2015-09-22 23:07 UTC
For example, [common_bodies.xacro](https://github.com/NASA-JSC-Robotics/val_description/blob/develop/model/robots/common/xacro/common_bodies.xacro) uses some relative path includes:

~~~
    <xacro:include filename="common/xacro/pelvis/pelvis.xacro" />
~~~

If I had an external package wanting to reuse this file, this would not be possible unless the include uses `$(find val_description)...` format, for example:

~~~
    <xacro:include filename="$(find val_description)/model/robots/common/xacro/pelvis/pelvis.xacro" />
~~~

Also, note the install target issue #15, it will have to change install command to something like below:

~~~
install(DIRECTORY model/
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}/model
)
~~~

**Comment by jlack1987** [comment] 2015-09-22 23:21
We recently had an issue with this. I was doing it with ${find val_description}, but in our bamboo build plans this was breaking our hydro builds so I had to change to relative paths(which I hate doing). @dustingooding any input here?

**Comment by hsu** [comment] 2015-09-22 23:31
have you tried keeping install target path and the path under source the same as suggested in issue #15?  Not sure if that'll work, but may be worth a try.

**Comment by jlack1987** [comment] 2015-09-22 23:46
I just pushed a fix to the install target location. I don't think that's going to fix the issue caused by the relative paths though.

**Comment by dustingooding** [comment] 2015-09-23 00:43
As @hsu suggests, it's very useful (if not required) to keep the install
location and the source locations looking the same for files found with
'rospack find'.

**Comment by jlack1987** [comment] 2015-09-23 01:25
Yeah but what about the relative path issue in the xacro's?

**Comment by dustingooding** [comment] 2015-09-23 14:25
Regarding the relative path issue...  A PackageX cannot call $(find) on itself.  PackageX is not listed in the ROS_PACKAGE_PATH until after you source setup.bash, and that only exists after you've built.  Chicken and egg.    There are tricks you can play (like manually adding your src tree to your ROS_PACKAGE_PATH, or building an empty workspace (to generate the setup.bash files) then add PackageX and build it....  but those are fragile.

An alternative approach is to put "depended on" xacros in PackageA and "depender" xacros in PackageB and PackageC, and identify some CMake target in PackageA that PackageB and PackageC can depend on to ensure PackageA is available and ready to be depended on.

Or, you could modify val_description and have it directly generate the artifacts you want.

**Comment by hsu** [comment] 2015-09-23 17:00
I tested this theory in pull request #17 and it seemed to compile without issues using `$(find val_description)` in [common_bodies.xacro](https://github.com/hsu/val_description-1/blob/develop/model/robots/common/xacro/common_bodies.xacro). And this change could let other packages include xacros installed by val_description.

**Comment by jlack1987** [comment] 2015-09-28 15:52
Ok so we had to maintain a hydro build, but we are now able to ditch our hydro build which was the root issue here. So we can now use $(find val_description) in the xacros. I will update this asap.

**Closed by jlack1987** 2015-09-28 15:52 UTC
